"""empty message

Revision ID: 38456310fbb3
Revises: 07c7b43d8518
Create Date: 2024-01-02 11:53:36.472842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38456310fbb3'
down_revision = '07c7b43d8518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('orders', app.models.JsonEncodedDict(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_order')
    # ### end Alembic commands ###
