"""empty message

Revision ID: 526fcab48dca
Revises: 327ad32a433d
Create Date: 2024-01-02 12:20:23.572551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526fcab48dca'
down_revision = '327ad32a433d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
