"""empty message

Revision ID: 80f34e25c1fd
Revises: 612be910cee3
Create Date: 2023-12-28 11:06:04.549112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f34e25c1fd'
down_revision = '612be910cee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('selling_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_price', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
