"""empty message

Revision ID: 90e3942fb79f
Revises: 526fcab48dca
Create Date: 2024-01-02 12:40:50.079124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e3942fb79f'
down_revision = '526fcab48dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
