"""empty message

Revision ID: a12847a6ce49
Revises: bac06e38bd33
Create Date: 2024-01-26 17:56:45.179603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12847a6ce49'
down_revision = 'bac06e38bd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('city')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
