"""empty message

Revision ID: e43cb3e88c78
Revises: f35bb1106728
Create Date: 2023-12-21 13:18:14.687404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43cb3e88c78'
down_revision = 'f35bb1106728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('pic_3')
        batch_op.drop_column('pic_2')
        batch_op.drop_column('pic_1')

    # ### end Alembic commands ###
